codecov:
  notify:
    after_n_builds: 6
  strict_yaml_branch: main

coverage:
  range: '50...90'
  status:
    project:
      default:
        target: auto
        threshold: 5%
        informational: true
    patch: off

flag_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        threshold: 2%
        informational: true

comment:
  require_changes: true
  after_n_builds: 6
